# Edit this Gemfile to bundle your application's dependencies.

gem "rubygems-update"
gem "bundler", "=0.8.1"
gem "bowline"

## Bundle the gems you use:
# gem "bj"
# gem "hpricot", "0.6"
# gem "sqlite3-ruby", :require_as => "sqlite3"
