# Edit this Gemfile to bundle your application's dependencies.
source 'http://rubygems.org'

gem "bundler", ">=0.9.19"
gem "bowline"

## Bundle the gems you use:
# gem "bj"
# gem "hpricot", "0.6"
# gem "sqlite3-ruby", :require => "sqlite3"