# Edit this Gemfile to bundle your application's dependencies.

gem "rubygems-update", "= 1.3.5"
gem "bundler08"
gem "bowline"

## Bundle the gems you use:
# gem "bj"
# gem "hpricot", "0.6"
# gem "sqlite3-ruby", :require_as => "sqlite3"